import {
  LayoutDashboard,
  FileText,
  Image as ImageIcon,
  Compass,
  Send,
  History,
  Globe,
  CornerUpRight,
  Search,
  Paintbrush,
  Tags,
  Smartphone,
  Blocks,
  Users,
  KeyRound,
  ShieldAlert,
  Bell,
  Mail,
  BarChart3,
  ArrowDownUp,
  ShieldCheck,
  Laptop,
  ShieldQuestion,
  Settings,
  Plug,
  Activity,
  Terminal,
  ListOrdered,
  FolderKanban,
  Package,
  Rocket,
  LucideIcon,
} from 'lucide-react';
import { CapabilityStatus } from '@/components/admin/CapabilityStatusBadge';
import { CapabilityGroup } from '@/components/admin/CapabilityShell';
import { HelpKey } from '@/lib/help/types';

export interface AdminNavItem {
  id: string;
  name: string;
  href: string;
  icon: LucideIcon;
  group: CapabilityGroup;
  status: CapabilityStatus;
  helpKey: HelpKey;
  description: string;
}

export interface AdminNavGroup {
  id: CapabilityGroup;
  name: string;
  items: AdminNavItem[];
}

export const ADMIN_NAV_GROUPS: AdminNavGroup[] = [
  {
    id: 'OBSAH',
    name: 'Obsah',
    items: [
      {
        id: 'dashboard',
        name: 'Přehled',
        href: '/admin',
        icon: LayoutDashboard,
        group: 'OBSAH',
        status: 'PROTOTYP',
        helpKey: 'admin.dashboard.view',
        description: 'Centrální přehled stavu publikace, aktivity redakce a rychlých akcí.',
      },
      {
        id: 'pages',
        name: 'Stránky',
        href: '/admin/pages',
        icon: FileText,
        group: 'OBSAH',
        status: 'PROTOTYP',
        helpKey: 'content.pages.view',
        description: 'Hierarchická struktura a správa všech stránek webu.',
      },
      {
        id: 'media',
        name: 'Média',
        href: '/admin/media',
        icon: ImageIcon,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.media.view',
        description: 'Knihovna obrázků, dokumentů a multimediálních aktiv.',
      },
      {
        id: 'navigation',
        name: 'Navigace',
        href: '/admin/navigation',
        icon: Compass,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.navigation.view',
        description: 'Správa navigačních nabídek, záhlaví, patičky a menu.',
      },
      {
        id: 'publishing',
        name: 'Publikování',
        href: '/admin/publishing',
        icon: Send,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.publishing.view',
        description: 'Publikační pipeline, neměnné verze a okamžitý rollback.',
      },
      {
        id: 'revisions',
        name: 'Revize',
        href: '/admin/revisions',
        icon: History,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.revisions.view',
        description: 'Historie změn a vizuální porovnání revizí obsahu.',
      },
      {
        id: 'seo',
        name: 'SEO',
        href: '/admin/seo',
        icon: Globe,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.seo.view',
        description: 'Globální SEO metadata, Open Graph a generátor sitemap.xml.',
      },
      {
        id: 'redirects',
        name: 'Přesměrování',
        href: '/admin/redirects',
        icon: CornerUpRight,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.redirects.view',
        description: 'Pravidla pro přesměrování URL adres (HTTP 301/302).',
      },
      {
        id: 'search',
        name: 'Vyhledávání',
        href: '/admin/search',
        icon: Search,
        group: 'OBSAH',
        status: 'UI PŘIPRAVENO',
        helpKey: 'content.search.view',
        description: 'Fulltextový index webu a statistiky hledaných výrazů.',
      },
    ],
  },
  {
    id: 'DESIGN',
    name: 'Design',
    items: [
      {
        id: 'themes',
        name: 'Vzhledy',
        href: '/admin/themes',
        icon: Paintbrush,
        group: 'DESIGN',
        status: 'UI PŘIPRAVENO',
        helpKey: 'design.themes.view',
        description: 'Vizuální témata, barevné palety a design tokeny.',
      },
      {
        id: 'brands',
        name: 'Značky',
        href: '/admin/brands',
        icon: Tags,
        group: 'DESIGN',
        status: 'UI PŘIPRAVENO',
        helpKey: 'design.brands.view',
        description: 'Logotypy, favicony, firemní barvy a identita organizace.',
      },
      {
        id: 'pwa',
        name: 'PWA',
        href: '/admin/pwa',
        icon: Smartphone,
        group: 'DESIGN',
        status: 'PLÁNOVÁNO',
        helpKey: 'design.pwa.view',
        description: 'Instalační manifest aplikace a správa offline režimu.',
      },
    ],
  },
  {
    id: 'SPRÁVA',
    name: 'Správa',
    items: [
      {
        id: 'modules',
        name: 'Moduly',
        href: '/admin/modules',
        icon: Blocks,
        group: 'SPRÁVA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'management.modules.view',
        description: 'Správa a aktivace funkčních modulů a rozšíření.',
      },
      {
        id: 'users',
        name: 'Uživatelé',
        href: '/admin/users',
        icon: Users,
        group: 'SPRÁVA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'management.users.view',
        description: 'Redakční tým, uživatelské účty a 2FA ověření.',
      },
      {
        id: 'roles',
        name: 'Role a oprávnění',
        href: '/admin/roles',
        icon: KeyRound,
        group: 'SPRÁVA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'management.roles.view',
        description: 'Přístupová práva (RBAC) a politika nejnižších privilegií.',
      },
      {
        id: 'audit',
        name: 'Audit',
        href: '/admin/audit',
        icon: ShieldAlert,
        group: 'SPRÁVA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'management.audit.view',
        description: 'Neměnný bezpečnostní protokol událostí a změn.',
      },
    ],
  },
  {
    id: 'KOMUNIKACE',
    name: 'Komunikace',
    items: [
      {
        id: 'notifications',
        name: 'Notifikace',
        href: '/admin/notifications',
        icon: Bell,
        group: 'KOMUNIKACE',
        status: 'UI PŘIPRAVENO',
        helpKey: 'communication.notifications.view',
        description: 'Centrum redakčních a systémových upozornění.',
      },
      {
        id: 'templates',
        name: 'Šablony zpráv',
        href: '/admin/templates',
        icon: Mail,
        group: 'KOMUNIKACE',
        status: 'PLÁNOVÁNO',
        helpKey: 'communication.templates.view',
        description: 'Transakční šablony e-mailů a notifikačních zpráv.',
      },
    ],
  },
  {
    id: 'DATA',
    name: 'Data',
    items: [
      {
        id: 'analytics',
        name: 'Analytika',
        href: '/admin/analytics',
        icon: BarChart3,
        group: 'DATA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'data.analytics.view',
        description: 'Statistiky návštěvnosti bez cookies v souladu s GDPR.',
      },
      {
        id: 'import-export',
        name: 'Import / Export',
        href: '/admin/import-export',
        icon: ArrowDownUp,
        group: 'DATA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'data.import_export.view',
        description: 'Portabilita celého webu, zálohování a obnova dat.',
      },
    ],
  },
  {
    id: 'BEZPEČNOST',
    name: 'Bezpečnost',
    items: [
      {
        id: 'security',
        name: 'Zabezpečení',
        href: '/admin/security',
        icon: ShieldCheck,
        group: 'BEZPEČNOST',
        status: 'UI PŘIPRAVENO',
        helpKey: 'security.overview.view',
        description: 'Bezpečnostní štít, TLS certifikáty a HTTP hlavičky.',
      },
      {
        id: 'sessions',
        name: 'Relace a zařízení',
        href: '/admin/sessions',
        icon: Laptop,
        group: 'BEZPEČNOST',
        status: 'UI PŘIPRAVENO',
        helpKey: 'security.sessions.view',
        description: 'Aktivní přihlášená zařízení a vzdálené odhlášení.',
      },
      {
        id: 'privacy',
        name: 'GDPR a soukromí',
        href: '/admin/privacy',
        icon: ShieldQuestion,
        group: 'BEZPEČNOST',
        status: 'UI PŘIPRAVENO',
        helpKey: 'security.privacy.view',
        description: 'Cookie lišta, souhlasy a správa ochrany osobních údajů.',
      },
    ],
  },
  {
    id: 'SYSTÉM',
    name: 'Systém',
    items: [
      {
        id: 'settings',
        name: 'Nastavení',
        href: '/admin/settings',
        icon: Settings,
        group: 'SYSTÉM',
        status: 'UI PŘIPRAVENO',
        helpKey: 'system.settings.view',
        description: 'Globální systémové parametry, lokalizace a režim údržby.',
      },
      {
        id: 'integrations',
        name: 'Integrace',
        href: '/admin/integrations',
        icon: Plug,
        group: 'SYSTÉM',
        status: 'UI PŘIPRAVENO',
        helpKey: 'system.integrations.view',
        description: 'Webhooky, externí služby a cloudová úložiště.',
      },
      {
        id: 'diagnostics',
        name: 'Diagnostika',
        href: '/admin/diagnostics',
        icon: Activity,
        group: 'SYSTÉM',
        status: 'UI PŘIPRAVENO',
        helpKey: 'system.diagnostics.view',
        description: 'Diagnostika běhového prostředí, databáze a paměti.',
      },
      {
        id: 'logs',
        name: 'Logy',
        href: '/admin/logs',
        icon: Terminal,
        group: 'SYSTÉM',
        status: 'UI PŘIPRAVENO',
        helpKey: 'system.logs.view',
        description: 'Živé systémové protokoly a chybová hlášení.',
      },
      {
        id: 'queues',
        name: 'Úlohy a fronty',
        href: '/admin/queues',
        icon: ListOrdered,
        group: 'SYSTÉM',
        status: 'PLÁNOVÁNO',
        helpKey: 'system.queues.view',
        description: 'Asynchronní úlohy na pozadí a plánovač Cron úloh.',
      },
    ],
  },
  {
    id: 'PLATFORMA',
    name: 'Platforma',
    items: [
      {
        id: 'projects',
        name: 'Projekty',
        href: '/admin/projects',
        icon: FolderKanban,
        group: 'PLATFORMA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'platform.projects.view',
        description: 'Přepínání projektů a správa vývojových prostředí.',
      },
      {
        id: 'project-packs',
        name: 'Project Packs',
        href: '/admin/project-packs',
        icon: Package,
        group: 'PLATFORMA',
        status: 'PLÁNOVÁNO',
        helpKey: 'platform.project_packs.view',
        description: 'Distribuční balíčky a certifikované sestavy modulů.',
      },
      {
        id: 'deployment',
        name: 'Deployment',
        href: '/admin/deployment',
        icon: Rocket,
        group: 'PLATFORMA',
        status: 'UI PŘIPRAVENO',
        helpKey: 'platform.deployment.view',
        description: 'Stav nasazení, Git SHA kontrolní součet a Cloud Run hosting.',
      },
    ],
  },
];

export const ALL_ADMIN_NAV_ITEMS = ADMIN_NAV_GROUPS.flatMap((g) => g.items);

export function getNavItemByPath(pathname: string): AdminNavItem | undefined {
  if (pathname === '/admin') {
    return ALL_ADMIN_NAV_ITEMS.find((item) => item.href === '/admin');
  }
  return ALL_ADMIN_NAV_ITEMS.find(
    (item) => item.href !== '/admin' && (pathname === item.href || pathname.startsWith(item.href + '/'))
  );
}
