import type { SvgSecurityReasonCode } from '../types';

export interface SecurityVector {
  readonly id: string;
  readonly category: string;
  readonly description: string;
  readonly input: string;
  readonly expectedPass: boolean;
  readonly expectedReasonCode?: SvgSecurityReasonCode;
}

export const SECURITY_VECTORS: readonly SecurityVector[] = [
  // 1. Script / Mixed Case / Encodings (Reject)
  {
    id: 'VEC-SCRIPT-001',
    category: 'script',
    description: 'Direct lowercase script tag',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCRIPT-002',
    category: 'script',
    description: 'Mixed case sCrIpt tag',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><sCrIpt>alert(1)</sCrIpt></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCRIPT-003',
    category: 'script',
    description: 'Uppercase SCRIPT tag with CDATA',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><SCRIPT><![CDATA[alert(1)]]></SCRIPT></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCRIPT-004',
    category: 'script',
    description: 'Script tag with external src attribute',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><script src="https://evil.com/xss.js" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCRIPT-005',
    category: 'script',
    description: 'Script tag with xlink:href',
    input: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><script xlink:href="https://evil.com/xss.js" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-SCRIPT-006',
    category: 'script',
    description: 'Script tag nested inside g',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g><g><script>alert(1)</script></g></g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCRIPT-007',
    category: 'script',
    description: 'Script pattern in text content',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><text><script>alert(1)</script></text></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },

  // 2. foreignObject (Reject)
  {
    id: 'VEC-FO-001',
    category: 'foreignObject',
    description: 'Standard foreignObject with HTML body',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><foreignObject width="100" height="100"><body xmlns="http://www.w3.org/1999/xhtml"><p>evil</p></body></foreignObject></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FOREIGN_OBJECT',
  },
  {
    id: 'VEC-FO-002',
    category: 'foreignObject',
    description: 'Mixed case FoReIgNoBjEcT',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><FoReIgNoBjEcT width="100" height="100"><iframe src="javascript:alert(1)" /></FoReIgNoBjEcT></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FOREIGN_OBJECT',
  },
  {
    id: 'VEC-FO-003',
    category: 'foreignObject',
    description: 'foreignObject nested inside g',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g><foreignObject width="50" height="50" /></g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FOREIGN_OBJECT',
  },

  // 3. iframe / object / embed / image / audio / video (Forbidden elements)
  {
    id: 'VEC-ELEM-001',
    category: 'forbidden_elements',
    description: 'iframe element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><iframe src="http://evil.com" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-002',
    category: 'forbidden_elements',
    description: 'object element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><object data="http://evil.com/test.swf" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-003',
    category: 'forbidden_elements',
    description: 'embed element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><embed src="http://evil.com/test.swf" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-004',
    category: 'forbidden_elements',
    description: 'image element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><image href="http://evil.com/pic.jpg" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-005',
    category: 'forbidden_elements',
    description: 'audio element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><audio src="http://evil.com/sound.mp3" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-006',
    category: 'forbidden_elements',
    description: 'video element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><video src="http://evil.com/clip.mp4" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-007',
    category: 'forbidden_elements',
    description: 'animate element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"><animate attributeName="x" from="0" to="10" dur="1s" /></rect></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-008',
    category: 'forbidden_elements',
    description: 'set element for SMIL injection',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><set attributeName="onfocus" to="alert(1)" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-009',
    category: 'forbidden_elements',
    description: 'use element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><use href="#shape" /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ELEM-010',
    category: 'forbidden_elements',
    description: 'a element (hyperlink)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><a href="https://google.com"><rect width="10" height="10"/></a></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },

  // 4. on* Event Handlers (Reject)
  {
    id: 'VEC-EVT-001',
    category: 'event_handlers',
    description: 'onload on root svg',
    input: '<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-002',
    category: 'event_handlers',
    description: 'onclick on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect onclick="alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-003',
    category: 'event_handlers',
    description: 'onmouseover on g',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g onmouseover="alert(1)"><circle r="5"/></g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-004',
    category: 'event_handlers',
    description: 'onerror event handler',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect onerror="alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-005',
    category: 'event_handlers',
    description: 'Mixed case ONLOAD on path',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><path ONLOAD="alert(1)" d="M0 0 L10 10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-006',
    category: 'event_handlers',
    description: 'onbegin SMIL event',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect onbegin="alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-EVT-007',
    category: 'event_handlers',
    description: 'onend SMIL event',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle onend="alert(1)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },

  // 5. href / xlink:href (Reject)
  {
    id: 'VEC-HREF-001',
    category: 'href_xlink',
    description: 'href on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect href="javascript:alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EXTERNAL_REFERENCE',
  },
  {
    id: 'VEC-HREF-002',
    category: 'href_xlink',
    description: 'xlink:href on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect xlink:href="javascript:alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-HREF-003',
    category: 'href_xlink',
    description: 'Mixed case xLinK:HrEf',
    input: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g xLinK:HrEf="#foo"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },

  // 6. Schemes (javascript, vbscript, data, blob, http, https, file) in attributes (Reject)
  {
    id: 'VEC-SCHEME-001',
    category: 'schemes',
    description: 'javascript: URI in fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="javascript:alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCHEME-002',
    category: 'schemes',
    description: 'vbscript: URI in stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle stroke="vbscript:msgbox(1)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-SCHEME-003',
    category: 'schemes',
    description: 'data: text/html URI in fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_UNSAFE_URL',
  },
  {
    id: 'VEC-SCHEME-004',
    category: 'schemes',
    description: 'blob: URI in stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><path stroke="blob:https://evil.com/1234" d="M0 0 L10 10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_UNSAFE_URL',
  },
  {
    id: 'VEC-SCHEME-005',
    category: 'schemes',
    description: 'http: external URI in fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="http://evil.com/leak" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EXTERNAL_REFERENCE',
  },
  {
    id: 'VEC-SCHEME-006',
    category: 'schemes',
    description: 'https: external URI in stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect stroke="https://evil.com/leak" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EXTERNAL_REFERENCE',
  },
  {
    id: 'VEC-SCHEME-007',
    category: 'schemes',
    description: 'file: local file URI in fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="file:///etc/passwd" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_UNSAFE_URL',
  },

  // 7. CSS url / style / class (Reject)
  {
    id: 'VEC-CSS-001',
    category: 'css',
    description: 'style element forbidden',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><style>rect { fill: red; }</style><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-CSS-002',
    category: 'css',
    description: 'style attribute forbidden',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect style="fill:red; background:url(javascript:alert(1))" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-CSS-003',
    category: 'css',
    description: 'class attribute forbidden',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect class="my-class" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-CSS-004',
    category: 'css',
    description: 'url() in fill attribute',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="url(#gradient)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-CSS-005',
    category: 'css',
    description: 'url() with external http target in stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle stroke="url(http://evil.com/test)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-CSS-006',
    category: 'css',
    description: 'url() with javascript in fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="url(javascript:alert(1))" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },

  // 8. DOCTYPE / DTD / XXE (Reject)
  {
    id: 'VEC-DTD-001',
    category: 'dtd_xxe',
    description: 'DOCTYPE entity declaration XXE attack',
    input: '<!DOCTYPE svg [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><svg xmlns="http://www.w3.org/2000/svg"><text>&xxe;</text></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-DTD-002',
    category: 'dtd_xxe',
    description: 'Simple public DOCTYPE declaration',
    input: '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg"></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-DTD-003',
    category: 'dtd_xxe',
    description: 'Billion laughs XML entity expansion DOCTYPE',
    input: '<!DOCTYPE lolz [<!ENTITY lol "lol"><!ENTITY lol2 "&lol;&lol;">]><svg xmlns="http://www.w3.org/2000/svg"><text>&lol2;</text></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },

  // 9. Processing Instructions (Reject)
  {
    id: 'VEC-PI-001',
    category: 'processing_instructions',
    description: 'xml-stylesheet processing instruction',
    input: '<?xml-stylesheet href="javascript:alert(1)"?><svg xmlns="http://www.w3.org/2000/svg"></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-PI-002',
    category: 'processing_instructions',
    description: 'Custom processing instruction inside svg',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><?custom instruction?><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },

  // 10. Malformed XML (Reject)
  {
    id: 'VEC-MALFORM-001',
    category: 'malformed_xml',
    description: 'Unclosed tags',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g><rect width="10" height="10"></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-MALFORM-002',
    category: 'malformed_xml',
    description: 'Mismatched closing tag',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"></circle></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-MALFORM-003',
    category: 'malformed_xml',
    description: 'Garbage non-XML text',
    input: 'Not an SVG at all!',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-MALFORM-004',
    category: 'malformed_xml',
    description: 'Unquoted attribute value',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect width=10 height=10 /></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },

  // 11. Multiple roots / Non-SVG Root (Reject)
  {
    id: 'VEC-ROOT-001',
    category: 'root',
    description: 'Multiple root elements',
    input: '<svg xmlns="http://www.w3.org/2000/svg"></svg><svg xmlns="http://www.w3.org/2000/svg"></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_PARSE_FAILED',
  },
  {
    id: 'VEC-ROOT-002',
    category: 'root',
    description: 'HTML root element with embedded svg',
    input: '<html><body><svg xmlns="http://www.w3.org/2000/svg"></svg></body></html>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ROOT-003',
    category: 'root',
    description: 'Div root element',
    input: '<div><rect width="10" height="10"/></div>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },

  // 12. Nested SVG (Reject)
  {
    id: 'VEC-NESTED-SVG-001',
    category: 'nested_svg',
    description: 'SVG root containing nested svg tag',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g><svg width="100" height="100"><rect width="10" height="10"/></svg></g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },

  // 13. Namespace tricks (Reject)
  {
    id: 'VEC-NS-001',
    category: 'namespace',
    description: 'Invalid default XML namespace',
    input: '<svg xmlns="http://www.w3.org/1999/xhtml"><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-NS-002',
    category: 'namespace',
    description: 'HTML elements qualified with custom namespace',
    input: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:h="http://www.w3.org/1999/xhtml"><h:script>alert(1)</h:script></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },

  // 14. Limits (Size, Nodes, Depth, Attributes, AttrLength) (Reject)
  {
    id: 'VEC-LIMIT-INPUT-001',
    category: 'limits',
    description: 'Exceeds maximum input bytes (over 512KB)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><!-- ' + 'x'.repeat(520 * 1024) + ' --></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_INPUT_TOO_LARGE',
  },
  {
    id: 'VEC-LIMIT-DEPTH-001',
    category: 'limits',
    description: 'Exceeds maximum depth (>32 levels)',
    input: '<svg xmlns="http://www.w3.org/2000/svg">' + '<g>'.repeat(35) + '<rect width="10" height="10"/>' + '</g>'.repeat(35) + '</svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_MAX_DEPTH_EXCEEDED',
  },
  {
    id: 'VEC-LIMIT-NODES-001',
    category: 'limits',
    description: 'Exceeds maximum node count (>1000 nodes)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g>' + '<rect width="1" height="1"/>'.repeat(1005) + '</g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_TOO_MANY_NODES',
  },
  {
    id: 'VEC-LIMIT-ATTRS-001',
    category: 'limits',
    description: 'Exceeds maximum attributes per node (>30 attrs)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect ' + Array.from({ length: 35 }, (_, i) => 'data-a' + i + '="val"').join(' ') + ' width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-LIMIT-ATTRLEN-001',
    category: 'limits',
    description: 'Exceeds maximum attribute length (>4096 chars)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M ' + '0 '.repeat(3000) + '"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },

  // 15. Safe MVP Elements and Attributes (PASS)
  {
    id: 'VEC-SAFE-001',
    category: 'safe_mvp',
    description: 'Minimal root SVG',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-002',
    category: 'safe_mvp',
    description: 'Safe rect element with dimensions and fill',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="50" fill="#ff0000" rx="5" ry="5" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-003',
    category: 'safe_mvp',
    description: 'Safe ellipse element with radius and stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><ellipse cx="50" cy="50" rx="40" ry="30" stroke="blue" stroke-width="2" fill="none" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-004',
    category: 'safe_mvp',
    description: 'Safe ellipse element',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 100"><ellipse cx="100" cy="50" rx="80" ry="30" fill="green" opacity="0.8" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-005',
    category: 'safe_mvp',
    description: 'Safe line element',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><line x1="0" y1="0" x2="100" y2="100" stroke="black" stroke-width="1.5" stroke-linecap="round" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-006',
    category: 'safe_mvp',
    description: 'Safe polyline element',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polyline points="0,0 20,20 40,10 60,40" fill="none" stroke="purple" stroke-linejoin="bevel" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-007',
    category: 'safe_mvp',
    description: 'Safe polygon element',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,5 90,90 10,90" fill="yellow" stroke="orange" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-008',
    category: 'safe_mvp',
    description: 'Safe path element with simple bezier and arc',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M10 10 H 90 V 90 H 10 Z" fill="cyan" stroke="gray" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-009',
    category: 'safe_mvp',
    description: 'Safe text element with plain text content',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 50"><text x="10" y="30" fill="black">Hello Synthesis CMS</text></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-010',
    category: 'safe_mvp',
    description: 'Safe group with nested children and transform',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><g transform="translate(10, 20)"><rect width="20" height="20" fill="red"/><ellipse cx="10" cy="10" rx="5" ry="5" fill="blue"/></g></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-011',
    category: 'safe_mvp',
    description: 'Multiple nested groups with allowed opacity attributes',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g opacity="0.5"><g fill-opacity="0.8"><rect width="10" height="10" stroke-opacity="0.9"/></g></g></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-012',
    category: 'safe_mvp',
    description: 'Safe complex path with multiple coordinates',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><path d="M 10,20 C 15,25 35,25 40,20 S 65,15 70,20 Q 80,40 60,60 T 20,80 Z" fill="none" stroke="#333" /></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-013',
    category: 'safe_mvp',
    description: 'Safe rotate transform on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10" transform="rotate(45 5 5)" fill="green"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-014',
    category: 'safe_mvp',
    description: 'Safe scale and translate transforms combined',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g transform="translate(5, 5) scale(2, 2)"><rect x="5" y="5" width="10" height="10"/></g></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-015',
    category: 'safe_mvp',
    description: 'Safe text with special harmless characters',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><text x="5" y="15">Synthesis CMS - Safe &amp; Sound 2026</text></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-016',
    category: 'safe_mvp',
    description: 'Safe dimensions specified with pixel unit',
    input: '<svg xmlns="http://www.w3.org/2000/svg" width="200px" height="150px"><rect width="50px" height="50px"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-017',
    category: 'safe_mvp',
    description: 'Safe percent units on stroke and opacity',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect width="50" height="50" opacity="50%" fill="#123456"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-018',
    category: 'safe_mvp',
    description: 'Safe line with stroke-linecap square',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><line x1="1" y1="1" x2="20" y2="20" stroke="#fff" stroke-linecap="square"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-019',
    category: 'safe_mvp',
    description: 'Safe polyline with stroke-linejoin miter',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><polyline points="1,1 5,10 15,20" stroke="#000" stroke-linejoin="miter"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-SAFE-020',
    category: 'safe_mvp',
    description: 'Safe empty group',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g></g></svg>',
    expectedPass: true,
  },

  // 16. Additional Advanced Security Vectors (Total >= 80)
  {
    id: 'VEC-ADV-001',
    category: 'schemes',
    description: 'Leading whitespace and tab in javascript: url',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="   	  javascript:alert(1)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-ADV-002',
    category: 'schemes',
    description: 'JavaSCRIPT mixed case in stroke',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle stroke="JavaSCRIPT:alert(1)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-ADV-003',
    category: 'event_handlers',
    description: 'onfocusin event handler on group',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><g onfocusin="alert(1)"><rect width="5" height="5"/></g></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-ADV-004',
    category: 'event_handlers',
    description: 'onfocusout event handler on circle',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle onfocusout="alert(1)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-ADV-005',
    category: 'event_handlers',
    description: 'onactivate event handler on text',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><text onactivate="alert(1)">Hi</text></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-ADV-006',
    category: 'event_handlers',
    description: 'onresize event handler on root svg',
    input: '<svg xmlns="http://www.w3.org/2000/svg" onresize="alert(1)"><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-ADV-007',
    category: 'event_handlers',
    description: 'onscroll event handler on root svg',
    input: '<svg xmlns="http://www.w3.org/2000/svg" onscroll="alert(1)"><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_EVENT_HANDLER_DETECTED',
  },
  {
    id: 'VEC-ADV-008',
    category: 'forbidden_elements',
    description: 'desc element (non-whitelisted metadata)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><desc>Description</desc><rect width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-009',
    category: 'forbidden_elements',
    description: 'title element (non-whitelisted metadata)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><title>My title</title><circle r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-010',
    category: 'forbidden_elements',
    description: 'metadata element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><metadata>Metadata</metadata></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-011',
    category: 'forbidden_elements',
    description: 'clipPath element (deferred to later milestone)',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><clipPath id="cp"><rect width="10" height="10"/></clipPath></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-012',
    category: 'forbidden_elements',
    description: 'pattern element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><pattern id="p"><rect width="10" height="10"/></pattern></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-013',
    category: 'forbidden_elements',
    description: 'linearGradient element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><linearGradient id="g"><stop offset="0%" stop-color="red"/></linearGradient></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-014',
    category: 'forbidden_elements',
    description: 'radialGradient element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><radialGradient id="rg"><stop offset="0%" stop-color="blue"/></radialGradient></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-015',
    category: 'forbidden_elements',
    description: 'mask element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><mask id="m"><rect width="10" height="10"/></mask></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-016',
    category: 'forbidden_elements',
    description: 'marker element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><marker id="mk"><circle r="5"/></marker></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-017',
    category: 'forbidden_elements',
    description: 'filter element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><filter id="f"><feGaussianBlur stdDeviation="2"/></filter></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ELEMENT',
  },
  {
    id: 'VEC-ADV-018',
    category: 'forbidden_attributes',
    description: 'filter attribute on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect filter="url(#f)" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-ADV-019',
    category: 'forbidden_attributes',
    description: 'clip-path attribute on circle',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><circle clip-path="url(#cp)" r="5"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-ADV-020',
    category: 'forbidden_attributes',
    description: 'mask attribute on path',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><path mask="url(#m)" d="M0 0 L10 10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_CSS_POLICY_VIOLATION',
  },
  {
    id: 'VEC-ADV-021',
    category: 'forbidden_attributes',
    description: 'arbitrary unknown attribute on line',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><line badattr="value" x1="0" y1="0" x2="10" y2="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-ADV-022',
    category: 'forbidden_attributes',
    description: 'data-* custom attribute on rect',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><rect data-test="bad" width="10" height="10"/></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_FORBIDDEN_ATTRIBUTE',
  },
  {
    id: 'VEC-ADV-023',
    category: 'script',
    description: 'javascript: protocol hidden in text node of text element',
    input: '<svg xmlns="http://www.w3.org/2000/svg"><text>javascript:alert(1)</text></svg>',
    expectedPass: false,
    expectedReasonCode: 'SVG_SCRIPT_DETECTED',
  },
  {
    id: 'VEC-ADV-024',
    category: 'safe_mvp',
    description: 'Safe polygon with multiple vertex pairs',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500"><polygon points="100,10 40,198 190,78 10,78 160,198" fill="purple" stroke="#444" stroke-width="2"/></svg>',
    expectedPass: true,
  },
  {
    id: 'VEC-ADV-025',
    category: 'safe_mvp',
    description: 'Safe SVG with self-closing rect and ellipse inside group',
    input: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><g fill="none" stroke="red"><rect x="0" y="0" width="10" height="10"/><ellipse cx="20" cy="20" rx="5" ry="5"/></g></svg>',
    expectedPass: true,
  },
];
